insert into public.products
  (title, slug, description, category, price, image_url, rating, badge, stock, features, featured, active)
values
  (
    'Deep Work for Modern Makers',
    'deep-work-modern',
    'A focused guide for students, builders, and creators who want to protect attention, design better routines, and produce meaningful work in a noisy world.',
    'Books',
    24,
    'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&q=80',
    4.9,
    'Bestseller',
    42,
    array['Practical focus systems for busy schedules', 'Printable weekly planning prompts', 'Case studies from readers, founders, and creators'],
    true,
    true
  ),
  (
    'Aura Daily Clarity Journal',
    'aura-journal',
    'A premium guided journal built around morning priorities, evening reflection, and small daily wins that compound over time.',
    'Productivity',
    18,
    'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80',
    4.8,
    'New',
    80,
    array['120 days of guided pages', 'Habit, energy, and mood tracking', 'Minimal layouts that keep writing friction-free'],
    true,
    true
  ),
  (
    'Creator Desk Essentials Kit',
    'creator-desk-kit',
    'A refined desk kit with sticky tabs, idea cards, a compact stand, and cable tools for people who learn, ship, and create every day.',
    'Creative Tools',
    49,
    'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
    4.7,
    'Bundle',
    24,
    array['Includes cards, tabs, stand, and organizer clips', 'Designed for small desks and dorm rooms', 'Pairs well with physical books and digital workflows'],
    true,
    true
  ),
  (
    'Mindful Reading Lamp',
    'mindful-reading-lamp',
    'A soft, adjustable lamp that makes late-night reading comfortable without turning your room into a harsh workspace.',
    'Wellness',
    36,
    'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
    4.6,
    'Staff pick',
    18,
    array['Warm dimmable light modes', 'Compact metal body with stable base', 'Great for reading corners and study desks'],
    false,
    true
  ),
  (
    'The Startup Bookshelf',
    'startup-bookshelf',
    'A concise reading path covering product thinking, customer research, pricing, and personal execution for early-stage builders.',
    'Books',
    32,
    'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=900&q=80',
    4.9,
    'Curated',
    35,
    array['Five-book learning path in one guide', 'Chapter-by-chapter implementation prompts', 'Made for first-time founders and indie makers'],
    false,
    true
  ),
  (
    'Focus Timer Cube',
    'focus-timer-cube',
    'A tactile timer for study blocks, writing sprints, and screen-free focus sessions. Flip it, start, and get back to the work.',
    'Productivity',
    22,
    'https://images.unsplash.com/photo-1501139083538-0139583c060f?auto=format&fit=crop&w=900&q=80',
    4.5,
    'Popular',
    64,
    array['Preset 5, 15, 30, and 60-minute modes', 'Silent and soft-alert options', 'Pocket-sized for campus, office, and travel'],
    false,
    true
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  price = excluded.price,
  image_url = excluded.image_url,
  rating = excluded.rating,
  badge = excluded.badge,
  stock = excluded.stock,
  features = excluded.features,
  featured = excluded.featured,
  active = excluded.active;
